Repository matter-labs/era-boojum-cuda, pull requests merged in 2023-10, with the labels that each got.

#13 Checks that denom_at_zero length is zero if lookup is unused
  boojum-cuda/src/ops_complex.rs
Labels: enhancement

#16 make the code compatible with CUDA 12.3
  cudart/src/execution.rs
Labels: enhancement

#17 fix latest linter warnings
  boojum-cuda/src/barycentric.rs
  boojum-cuda/src/ops_complex.rs
  boojum-cuda/src/ops_cub/device_radix_sort.rs
  boojum-cuda/src/ops_cub/device_scan.rs
  cudart/src/execution.rs
Labels: refactoring

#18 fix gather_merkle_paths function
  boojum-cuda/native/poseidon_common.cu
  boojum-cuda/src/poseidon.rs
Labels: bug
